### ISSUE TITLE
cannot subscribe !

### ISSUE THREAD

**Issue by Moshe-Malka** [charany1/MQTT-Subscriber#1]
nullpointerexception accures when tryung to sub.
have you maneged to solve this problam?

**Comment by charany1** [comment]
I'm sorry for late response .
can you please paste your error logcat ?

**Comment by blaine12100** [comment]
Here is my logcat for the same issue.I've created a function to connect to the broker and i'm creating an object to call this connect function.Other functions using this object are working flawlessly.

07-18 16:07:38.707 2359-2359/com.example.dhruvmarwha.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.example.dhruvmarwha.myapplication, PID: 2359
                                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.dhruvmarwha.myapplication/com.example.dhruvmarwha.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.android.service.MqttService.subscribe(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String)' on a null object reference
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.android.service.MqttService.subscribe(java.lang.String, java.lang.String, int, java.lang.String, java.lang.String)' on a null object reference
                                                                                         at org.eclipse.paho.android.service.MqttAndroidClient.subscribe(MqttAndroidClient.java:906)
                                                                                         at org.eclipse.paho.android.service.MqttAndroidClient.subscribe(MqttAndroidClient.java:841)
                                                                                         at com.example.dhruvmarwha.myapplication.MainActivity.onCreate(MainActivity.java:120)
                                                                                         at android.app.Activity.performCreate(Activity.java:6980)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                         at android.os.Looper.loop(Looper.java:164) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6540) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
